on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 2 * * *'

name: 'Daily W3C Validation'

jobs:
  validate:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    name: 'Validate against W3C'
    strategy:
      matrix:
        url:
          - https://www.iut.u-bordeaux-montaigne.fr/
          - https://www.iut.u-bordeaux-montaigne.fr/notre-institut/presentation-de-liut/
          - https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/
          - https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/
          - https://www.iut.u-bordeaux-montaigne.fr/actualites/
          - https://www.iut.u-bordeaux-montaigne.fr/actualites/2024-11-20-des-violentometres-geants-poses-au-sol-pour-sensibiliser-aux-violences-sexistes-et-sexuelles/
          - https://www.iut.u-bordeaux-montaigne.fr/vie-etudiante/services-numeriques/wifi-universitaire/
    steps:
      - name: Send request to W3C with URL to validate
        run: |
          curl -G "https://validator.w3.org/nu/" --data-urlencode "doc=${{ matrix.url }}" --data-urlencode "out=json" > w3c-response.json
      - name: Send JSON response to webhook
        run: |
          curl --write-out '%{http_code}' --silent --output /dev/null -X POST -H "Content-Type: application/json" -H "X-Secret-Token: ${{ secrets.W3C_CI_API_SECRET }}" -d @w3c-response.json ${{ secrets.W3C_CI_API_URL }}
